# Generated by Django 4.2.2 on 2023-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.URLField(default='SOME STRING'),
        ),
    ]
